#!/bin/bash

TYPE=RELEASE

BASE_DIR=/opt/trilinos/source
INSTALL_DIR=/opt/trilinos/install

rm -rf CMake*

cmake \
    -D CMAKE_BUILD_TYPE:STRING=$TYPE \
    -D CMAKE_INSTALL_PREFIX:STRING=$INSTALL_DIR \
    -D CMAKE_C_FLAGS:STRING="-DFROSCH_TIMER_DETAILS=2" \
    -D CMAKE_CXX_FLAGS:STRING="-DFROSCH_TIMER_DETAILS=2" \
    -D CMAKE_CXX_STANDARD:STRING=14 \
    -D MPI_EXEC_MAX_NUMPROCS:STRING=8 \
    -D Trilinos_ENABLE_Fortran:BOOL=ON \
    -D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
    -D Trilinos_ASSERT_MISSING_PACKAGES:BOOL=ON \
    -D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
    -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
    -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
    -D Trilinos_VERBOSE_CONFIGURE:BOOL=OFF \
    -D Trilinos_ENABLE_Belos:BOOL=ON \
    -D Kokkos_ENABLE_SERIAL:BOOL=ON \
    -D Kokkos_ENABLE_TESTS:BOOL=ON \
    -D Trilinos_ENABLE_MueLu:BOOL=ON \
    -D Trilinos_ENABLE_ShyLU_DD:BOOL=ON \
    -D ShyLU_DDBDDC_ENABLE_TESTS:BOOL=OFF \
    -D ShyLU_DD_ENABLE_TESTS:BOOL=ON \
    -D Trilinos_ENABLE_Stratimikos:BOOL=ON \
    -D Tpetra_ENABLE_DEPRECATED_CODE:BOOL=ON \
    -D Trilinos_ENABLE_Thyra:BOOL=ON \
    -D Xpetra_ENABLE_DEPRECATED_CODE:BOOL=ON \
    -D TPL_ENABLE_MPI:BOOL=ON \
    -D TPL_ENABLE_BLAS:BOOL=ON \
    -D TPL_BLAS_LIBRARIES:FILEPATH=/usr/lib64/libblas.so.3 \
    -D TPL_ENABLE_Boost:BOOL=OFF \
    -D TPL_ENABLE_LAPACK:BOOL=ON \
    -D TPL_LAPACK_LIBRARIES:FILEPATH=/usr/lib64/liblapack.so.3 \
    -D TPL_ENABLE_Netcdf:BOOL=OFF \
    -D TPL_ENABLE_UMFPACK:BOOL=ON \
    -D UMFPACK_INCLUDE_DIRS:FILEPATH=/opt/suitesparse/install/include \
    -D UMFPACK_LIBRARY_DIRS:FILEPATH=/opt/suitesparse/install/lib \
    -D TPL_ENABLE_X11:BOOL=OFF \
$BASE_DIR
